name: Nummern
options:
  bundleIdPrefix: com.digitalhandstand
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    ENABLE_GENERATED_ASSET_SYMBOL_EXTENSIONS: YES
    STRING_CATALOG_GENERATE_SYMBOLS: YES
targets:
  Nummern:
    type: application
    platform: macOS
    sources:
      - path: Nummern
    resources:
      - path: Nummern/Assets.xcassets
      - path: python
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalhandstand.nummern
        INFOPLIST_FILE: Config/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        SWIFT_VERSION: 5.9
        DEAD_CODE_STRIPPING: YES
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        STRING_CATALOG_GENERATE_SYMBOLS: YES
  NummernTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: NummernTests
    dependencies:
      - target: Nummern
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.9
        DEAD_CODE_STRIPPING: YES
        ENABLE_USER_SCRIPT_SANDBOXING: YES
schemes:
  Nummern:
    build:
      targets:
        Nummern: all
    test:
      targets:
        - NummernTests
